### ISSUE TITLE
node v4 compat issue

### ISSUE THREAD

**Issue by jeromecovington** [mrDarcyMurphy/node-rmrf#3]
Running into a node v4.2.1 compatibility issue here - https://github.com/mrDarcyMurphy/node-rmrf/blob/master/index.js#L4 - with the `fs.existsSync` method, which has been deprecated - https://nodejs.org/api/fs.html#fs_fs_existssync_path - any thoughts on supporting v4?

**Comment by mrDarcyMurphy** [comment]
https://nodejs.org/api/fs.html#fs_fs_existssync_path
> Note that fs.exists() is deprecated, but fs.existsSync() is not.
