### ISSUE TITLE
Typings not correct

### ISSUE THREAD

**Issue by szz-dvl** [mrDarcyMurphy/node-rmrf#7]
Hi!

I'm trying to use your module with typescript 3.4.5, I think that the types for this module are not correct, concretely you have:

`
declare namespace rmfr {
    type Options = rimraf.Options & {
        glob?: rimraf.Options["glob"] | true;
        disableGlob?: never;
    };
}
`

This will never accept `glob: true` as an option, so, right now I'm using: 

`
declare namespace rmfr {
    type Options = rimraf.Options | {
        glob?: rimraf.Options["glob"] | true;
        disableGlob?: never;
    };
}
` 
I'm not a typescript expert so correct me if I'm mistaken. Hope it helps anyway.

Szz.

**Comment by mrDarcyMurphy** [comment]
Thanks for the heads up. I'll take a look.

**Comment by mrDarcyMurphy** [comment]
@szz-dvl I've added a types file and published the update, but I'm not sure if that'll help your case since this isn't [rimraf](https://www.npmjs.com/package/rimraf).

**Comment by szz-dvl** [comment]
@mrDarcyMurphy Thanks, sorry for the delay and thanks! I will try it as soon as possible
